### ISSUE TITLE
Performance issue: Frequently GC

### ISSUE THREAD

**Issue by walfud** [matthewrkula/SecretTextView#7]
Tks for your nice code first, but...
while running your demo, I found the memory usage like this (tested on Genymotion 2.4 with intel acceleration, x64, android 5.1.0 on nexus 4):
![image](https://cloud.githubusercontent.com/assets/9317897/7955878/3407aff2-0a0e-11e5-87a3-f5aa23937cee.png)

Obviously, it's cause by:
![image](https://cloud.githubusercontent.com/assets/9317897/7956028/aa7112d6-0a0f-11e5-89f6-1d3577987162.png)

-----------------

I have fix that problem, pls see you pull request.
The work I did is:
1, Use a `MutableForegroundColorSpan` to maintain the foreground color, instead new a `ForeGroundColorSpan` every time.
2, Change the `MutableForegroundColorSpan` object's color when needed.

Here is memory usage after my fix(tested on Genymotion 2.4 with intel acceleration, x64, android 5.1.0 on nexus 4):
![image](https://cloud.githubusercontent.com/assets/9317897/7956181/d357259a-0a10-11e5-829a-e7cf3d3040f0.png)

**Comment by mattkula** [comment]
Fixed with  c62c38fd
